/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAL.ProdutoDAL;
import DAL.UsuarioDAL;
import Entidades.Produto;
import Entidades.Sessao.Session;
import Entidades.TipoProduto;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.ZonedDateTime;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


/**
 *
 * @author Felipe
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        setLocationRelativeTo(null);
        listaTipoUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelCadastroProd = new javax.swing.JLabel();
        jLabelNomeProd = new javax.swing.JLabel();
        jLabelTipoProd = new javax.swing.JLabel();
        jLabelValorPago = new javax.swing.JLabel();
        jLabelValorVenda = new javax.swing.JLabel();
        jTextNomeProd = new javax.swing.JTextField();
        jTextValorPago = new javax.swing.JTextField();
        jTextValorVenda = new javax.swing.JTextField();
        jComboTipo = new javax.swing.JComboBox<>();
        jButtonNovoTipo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextQuantidade = new javax.swing.JTextField();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCadastroProd.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabelCadastroProd.setText("Cadastro de produto");

        jLabelNomeProd.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelNomeProd.setText("Nome do produto:");

        jLabelTipoProd.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelTipoProd.setText("Tipo do produto:");

        jLabelValorPago.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelValorPago.setText("Valor pago:");

        jLabelValorVenda.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelValorVenda.setText("Valor venda:");

        jTextNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeProdActionPerformed(evt);
            }
        });
        jTextNomeProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomeProdKeyTyped(evt);
            }
        });

        jTextValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextValorPagoKeyTyped(evt);
            }
        });

        jTextValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextValorVendaKeyTyped(evt);
            }
        });

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jButtonNovoTipo.setText("Novo");
        jButtonNovoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoTipoActionPerformed(evt);
            }
        });
        jButtonNovoTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonNovoTipoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade:");

        jTextQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextQuantidadeKeyTyped(evt);
            }
        });

        jButtonFinalizar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomeProd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextValorPago, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 280, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoTipo))
                    .addComponent(jLabelCadastroProd)
                    .addComponent(jTextValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonFinalizar)
                .addGap(47, 47, 47)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelCadastroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinalizar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeProdActionPerformed
      
    }//GEN-LAST:event_jTextNomeProdActionPerformed

    private void jButtonNovoTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovoTipoKeyTyped
        
    }//GEN-LAST:event_jButtonNovoTipoKeyTyped

    private void jTextNomeProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeProdKeyTyped
        if(jTextNomeProd.getText().length() >= 50){
            evt.consume();
        }
    }//GEN-LAST:event_jTextNomeProdKeyTyped
    
    private void jTextQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextQuantidadeKeyTyped
        if(jTextQuantidade.getText().length() >= 10){
            evt.consume();
        }
        
        class jTextQuantidade extends PlainDocument{
        
        @Override
        
        public void insertString(int offs, String str, 
            AttributeSet a) throws BadLocationException{
            char digito;
            boolean numerico = true;
 
            for(int i = 0; i < str.length(); i++){
            digito = str.charAt(i);
 
            if(!Character.isDigit(digito)){
            numerico = false;
            break;
      }
            
        if(numerico)
        super.insertString(offs, str, a);
            
            }
          }
        }
    }//GEN-LAST:event_jTextQuantidadeKeyTyped

    private void jTextValorVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextValorVendaKeyTyped
        if(jTextValorVenda.getText().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_jTextValorVendaKeyTyped

    private void jTextValorPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextValorPagoKeyTyped
        if(jTextValorPago.getText().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_jTextValorPagoKeyTyped

    private void jButtonNovoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoTipoActionPerformed
        new CadastroTipoProduto().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNovoTipoActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        try {
            boolean retorno = ValidaCadastro();
       
            if(retorno){
                Produto produto = new Produto();
                TipoProduto tipoProduto = new TipoProduto();
                produto.setIdUsuarioCadastro(Session.ID_Usuario);
                produto.setNome(jTextNomeProd.getText());
                produto.setVL_Pago(Double.parseDouble(jTextValorPago.getText()));
                produto.setVL_Venda(Double.parseDouble(jTextValorVenda.getText()));
                produto.setQuantidade(Integer.parseInt(jTextQuantidade.getText()));
                //tipoProduto.setIdTipoProduto();
                //produto.setTipoProduto(tipoProduto);
           
                ProdutoDAL produtoDAL = new ProdutoDAL();
                if(produtoDAL.criarProduto(produto)){
                    JOptionPane.showMessageDialog(null,"Produto cadastrado","Atenção", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                } else {
               
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+ e.getMessage(),"Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private boolean ValidaCadastro(){
        String mensagem = "";
        int erro = 0;
        
        if (jTextNomeProd.getText().equals("")){
            mensagem += "Digite o nome!\n";
            erro++;
        }
        
        if (jTextQuantidade.getText().equals("")){
            mensagem += "Digite a quantidade!\n";
            erro++;
        }
        
        if (jTextValorVenda.getText().equals("")){
            mensagem += "Digite o valor de venda!\n";
            erro++;
        }
        
        if (jTextValorPago.getText().equals("")){
            mensagem += "Digite o valor de compra!\n";
            erro++;
        }
        if (erro  >  0){
           JOptionPane.showMessageDialog(null, mensagem, "Atenção", JOptionPane.CANCEL_OPTION);
       }       
       
       return erro == 0;

    }
    
    public void listaTipoUsuario(){
        try {
            ProdutoDAL produtoDAL = new ProdutoDAL();
            ResultSet res = produtoDAL.listaTipoProduto();
            
            while (res.next()){
                jComboTipo.addItem(res.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonNovoTipo;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadastroProd;
    private javax.swing.JLabel jLabelNomeProd;
    private javax.swing.JLabel jLabelTipoProd;
    private javax.swing.JLabel jLabelValorPago;
    private javax.swing.JLabel jLabelValorVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextNomeProd;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jTextValorPago;
    private javax.swing.JTextField jTextValorVenda;
    // End of variables declaration//GEN-END:variables
}
