package GUI;

import DAL.ClienteDAL;
import DAL.UsuarioDAL;
import Entidades.Cliente;
import Entidades.Sessao.Session;
import Entidades.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55119
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Clientes() {
        initComponents();
        carregaTabelaClientes();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCriar = new javax.swing.JButton();

        jTableClientes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nome", "E-mail", "CPF/CNPJ"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        jButtonAtualizar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonDeletar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonCriar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int idCliente = jTableClientes.getSelectedRow();
        
        if(idCliente < 0){
            JOptionPane.showMessageDialog(null,"Selecione o cliente para conseguir atualizar! ","Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(Session.ID_TipoUsuario == 2){
            JOptionPane.showMessageDialog(null, "Somente administradores.", "Atenção", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        new CadastroCliente(idCliente).setVisible(true);
        setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int index = jTableClientes.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(null,"Selecione o cliente para conseguir deletar! ","Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(Session.ID_TipoUsuario == 2){
            JOptionPane.showMessageDialog(null, "Somente administradores.", "Atenção", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            ClienteDAL dal = new ClienteDAL();
            Cliente cliente = dal.listarClientes().get(index);
            dal.deletarCliente(cliente.getIdCliente());
            carregaTabelaClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        
        if(Session.ID_TipoUsuario == 2){
            JOptionPane.showMessageDialog(null, "Somente administradores.", "Atenção", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new CadastroCliente().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }
    
    private void carregaTabelaClientes(){
        DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        modelo.setNumRows(0);
        
        jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        try {
            ClienteDAL clienteDAL = new ClienteDAL();
        
        for (Cliente c : clienteDAL.listarClientes()){
            modelo.addRow(new Object[]{
                c.getIdCliente(),
                c.getNome(),
                c.getEmail(),
                c.getCpfCnpj()
            });
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
