package GUI;

import DAL.RelatorioDAL;
import Entidades.Relatorio;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Humberto Ramone
 */
public class GerarRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public GerarRelatorio() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabelDataIn.setVisible(false);
        jLabelDataFim.setVisible(false);
        jFormattedTextDataInicial.setVisible(false);
        jFormattedTextDataFinal.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDataIn = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        jFormattedTextDataInicial = new javax.swing.JFormattedTextField();
        jFormattedTextDataFinal = new javax.swing.JFormattedTextField();
        jLabelDataFim = new javax.swing.JLabel();
        jButtonGerar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero do pedido", "Nome Cliente", "Forma de pagamento", "Status", "Data", "Nome do produto", "Quantidade", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorio);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setText("Filtro:");

        jLabelDataIn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabelDataIn.setText("Data inicial:");

        jComboTipo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas as vendas", "Por período" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        jFormattedTextDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelDataFim.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabelDataFim.setText("Até:");

        jButtonGerar.setText("Gerar");
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataIn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFormattedTextDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabelDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDataIn)
                    .addComponent(jFormattedTextDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataFim)
                        .addComponent(jFormattedTextDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jButtonFechar.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFechar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButtonFechar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFechar.setText("X");
        jButtonFechar.setPreferredSize(new java.awt.Dimension(28, 28));
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1128, Short.MAX_VALUE)
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        try {
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
            if ("Por período".equals(jComboTipo.getSelectedItem().toString()) && "".equals(jFormattedTextDataInicial.getText())){
                JOptionPane.showMessageDialog(null,"Digite a data inicial.","Atenção", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if ("Por período".equals(jComboTipo.getSelectedItem().toString()) && "".equals(jFormattedTextDataFinal.getText())){
                JOptionPane.showMessageDialog(null,"Digite a data final.","Atenção", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if ("Por período".equals(jComboTipo.getSelectedItem().toString())){
                Date dtInicial = dt.parse(jFormattedTextDataInicial.getText());
                Date dtFinal = dt.parse(jFormattedTextDataFinal.getText());
                gerarRelatorioPorPeriodo(dtInicial,dtFinal);
            } else {
                gerarRelatorioCompleto();
            }
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        jLabelDataIn.setVisible("Por período".equals(jComboTipo.getSelectedItem().toString()));
        jLabelDataFim.setVisible("Por período".equals(jComboTipo.getSelectedItem().toString()));
        jFormattedTextDataInicial.setVisible("Por período".equals(jComboTipo.getSelectedItem().toString()));
        jFormattedTextDataFinal.setVisible("Por período".equals(jComboTipo.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboTipoActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharActionPerformed
    
    private void gerarRelatorioPorPeriodo(Date inicio, Date fim){
        DefaultTableModel modelo = (DefaultTableModel) jTableRelatorio.getModel();
        modelo.setNumRows(0);
        
        jTableRelatorio.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableRelatorio.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableRelatorio.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableRelatorio.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        try {
            RelatorioDAL relatorioDAL = new RelatorioDAL();
        
        for (Relatorio r : relatorioDAL.listarRelatorio(inicio, fim)){
            modelo.addRow(new Object[]{
                r.IdPedido,
                r.NomeCliente,
                r.FormaPagamento,
                r.PedidoStatus,
                r.DataVenda,
                r.NomeProduto,
                r.Quantidade,
                r.Total
            });
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void gerarRelatorioCompleto(){
        DefaultTableModel modelo = (DefaultTableModel) jTableRelatorio.getModel();
        modelo.setNumRows(0);
        
        jTableRelatorio.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableRelatorio.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableRelatorio.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableRelatorio.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        try {
            RelatorioDAL relatorioDAL = new RelatorioDAL();
        
        for (Relatorio r : relatorioDAL.listarRelatorio()){
            modelo.addRow(new Object[]{
                r.IdPedido,
                r.NomeCliente,
                r.FormaPagamento,
                r.PedidoStatus,
                r.DataVenda,
                r.NomeProduto,
                r.Quantidade,
                r.Total
            });
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Contate o administrador\nErro: "+e.getMessage(),"Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JFormattedTextField jFormattedTextDataFinal;
    private javax.swing.JFormattedTextField jFormattedTextDataInicial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDataFim;
    private javax.swing.JLabel jLabelDataIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorio;
    // End of variables declaration//GEN-END:variables
}
